name: ConfigKey
fields:
  - name: Text
  - name: Label
  - name: Unknown0
  - name: Param
  - name: Platform
  - name: Category
  - name: BacklightColor
    type: link
    targets: [BacklightColor]
  - name: Required